  // Updated publications data matching your list
  export const publicationsData = [
    // First author publications
    {
      id: 1,
      title: "In-plane anomalous Hall effect in a low-dimensional system",
      authors: ["I-Hsuan Kao†", "B. Ravi Kumar†", "et al."],
      journal: "Nature Materials",
      year: 2026,
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      isEquallyContributed: true,
      impactFactor: 43.1,
      citations: 0,
      link: "https://www.nature.com/articles/s41563-026-02611-9",
      doi: "https://doi.org/10.1038/s41563-026-02611-9",
      abstract: "First author publication in Nature Materials on in-plane anomalous Hall effect in low-dimensional systems.",
      keywords: ["Anomalous Hall Effect", "Low-dimensional systems", "Spintronics", "Quantum materials"]
    },
    {
      id: 2,
      title: "Tuning the interfacial Dzyaloshinskii–Moriya interaction in perpendicularly magnetized CoFeB system",
      authors: ["B. Ravi Kumar", "et al."],
      journal: "Journal of Physics D: Applied Physics",
      year: 2022,
      volume: "55",
      pages: "445004",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 3.4,
      citations: 15,
      link: "https://iopscience.iop.org/article/10.1088/1361-6463/ac8e77/meta",
      doi: "10.1088/1361-6463/ac8e77",
      abstract: "Investigates manipulation of Dzyaloshinskii-Moriya interaction in CoFeB thin films for spintronic applications.",
      keywords: ["DMI", "CoFeB", "Thin films", "Spintronics", "Magnetic anisotropy"]
    },
    {
      id: 3,
      title: "Enhancing the properties of CdO thin films by co-doping with Mn and Fe for photodetector applications",
      authors: ["B. Ravi Kumar", "et al."],
      journal: "Sensors and Actuators",
      year: 2021,
      volume: "219",
      pages: "112544",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 4.2,
      citations: 9,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0924424721000054",
      doi: "10.1016/j.sna.2021.112544",
      abstract: "Improves CdO thin film properties through co-doping for photodetector applications.",
      keywords: ["CdO", "Thin films", "Doping", "Photodetectors", "Optoelectronics"]
    },
    {
      id: 4,
      title: "Anomalous softening of magnon modes in the reentrant state in Cr70Fe30 thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "J. Magn. Magn. Mater.",
      year: 2019,
      volume: "469",
      pages: "681",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 2.9,
      citations: 12,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0304885318314860",
      doi: "10.1016/j.jmmm.2018.08.091",
      abstract: "Studies magnon mode softening in reentrant magnetic states of CrFe thin films.",
      keywords: ["Magnons", "CrFe alloys", "Thin films", "Reentrant state", "Magnetic excitations"]
    },
    {
      id: 5,
      title: "Thickness as a control parameter for magnetocaloric effect in Cr75−xFe25+x (x = 0, 5) thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "J. Magn. Magn. Mater.",
      year: 2018,
      volume: "460",
      pages: "312",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 2.9,
      citations: 18,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S030488531830091X",
      doi: "10.1016/j.jmmm.2018.03.064",
      abstract: "Explores thickness-dependent magnetocaloric effects in CrFe alloy thin films.",
      keywords: ["Magnetocaloric", "Thin films", "CrFe alloys", "Cooling applications", "Thickness dependence"]
    },
    {
      id: 6,
      title: "Isotropic-Heisenberg to isotropic-dipolar crossover and finite-size scaling in Cr75−xFe25+x (x = 0, 5) thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "J. Mag. Magn. Mater.",
      year: 2018,
      volume: "448",
      pages: "3",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 2.9,
      citations: 10,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0304885317301336",
      doi: "10.1016/j.jmmm.2017.09.074",
      abstract: "Investigates magnetic interaction crossovers and finite-size effects in thin films.",
      keywords: ["Heisenberg model", "Dipolar interactions", "Finite-size scaling", "Thin films", "Critical phenomena"]
    },
    {
      id: 7,
      title: "Nature of reentrant state in Cr75−xFe25+x (x = 0, 5) thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "J. Magn. Magn. Mater.",
      year: 2016,
      volume: "401",
      pages: "539",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 2.9,
      citations: 14,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0304885316302396",
      doi: "10.1016/j.jmmm.2016.07.023",
      abstract: "Characterizes the reentrant magnetic state in CrFe thin film systems.",
      keywords: ["Reentrant magnetism", "Spin glass", "Thin films", "Magnetic phases", "Disorder"]
    },
    {
      id: 8,
      title: "Magnetic order-disorder phase transition in Cr70Fe30 thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "J. Alloys Compd.",
      year: 2015,
      volume: "652",
      pages: "479",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 4.6,
      citations: 22,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0925838815308690",
      doi: "10.1016/j.jallcom.2015.08.256",
      abstract: "Studies magnetic phase transitions in CrFe alloy thin films.",
      keywords: ["Phase transitions", "Order-disorder", "Thin films", "CrFe alloys", "Magnetism"]
    },
    {
      id: 9,
      title: "Irreversibility lines in the T-H phase diagram of Cr70Fe30 thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "Physica B",
      year: 2014,
      volume: "448",
      pages: "140",
      type: "journal",
      category: "first-author",
      isFirstAuthor: true,
      impactFactor: 1.9,
      citations: 8,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0921452614002567",
      doi: "10.1016/j.physb.2014.03.064",
      abstract: "Maps irreversibility lines in temperature-field phase diagrams of thin films.",
      keywords: ["Phase diagrams", "Irreversibility", "Thin films", "Magnetic fields", "Temperature dependence"]
    },

    // Co-author publications
    {
      id: 10,
      title: "Electrocatalytic Degradation of Rhodamine B Using Li-Doped ZnO Nanoparticles: Novel Approach",
      authors: ["Vanga Ganesh", "B. Ravi Kumar", "et al."],
      journal: "Materials",
      year: 2023,
      volume: "16",
      pages: "1177",
      type: "journal",
      category: "co-author",
      isFirstAuthor: false,
      impactFactor: 3.4,
      citations: 3,
      link: "https://www.mdpi.com/1996-1944/16/3/1177",
      doi: "10.3390/ma16031177",
      abstract: "Study on electrocatalytic degradation using Li-doped ZnO nanoparticles.",
      keywords: ["ZnO nanoparticles", "Electrocatalysis", "Doping", "Water treatment", "Rhodamine B"]
    },
    {
      id: 11,
      title: "Structural, electrical, and optical properties of rare-earth Sm3+ doped SnO2 transparent conducting oxide thin films for optoelectronic device applications: Synthesized by the spin coating method",
      authors: ["Harish", "B. Ravi Kumar", "et al."],
      journal: "Optical Materials",
      year: 2022,
      volume: "133",
      pages: "112993",
      type: "journal",
      category: "co-author",
      isFirstAuthor: false,
      impactFactor: 3.7,
      citations: 6,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0925346722010308",
      doi: "10.1016/j.optmat.2022.112993",
      abstract: "Characterizes Sm-doped SnO2 thin films for transparent conducting applications.",
      keywords: ["SnO2", "Transparent conductors", "Thin films", "Optoelectronics", "Doping"]
    },
    {
      id: 12,
      title: "Lattice effects on the multiferroic characteristics of (La, Ho) co-substituted BiFeO3",
      authors: ["Pittala Suresh", "B. Ravi Kumar", "et al."],
      journal: "J. Alloys Compd.",
      year: 2021,
      volume: "863",
      pages: "158719",
      type: "journal",
      category: "co-author",
      isFirstAuthor: false,
      impactFactor: 4.6,
      citations: 11,
      link: "https://www.sciencedirect.com/science/article/abs/pii/S0925838821001262",
      doi: "10.1016/j.jallcom.2021.158719",
      abstract: "Investigates lattice effects on multiferroic properties of doped BiFeO3.",
      keywords: ["Multiferroics", "BiFeO3", "Lattice effects", "Doping", "Ferroelectricity"]
    },
    {
      id: 13,
      title: "Structural, Optical and Dielectric Properties of Nd Doped NiO Thin Films Deposited with a Spray Pyrolysis Method",
      authors: ["V. Ganesh", "B. Ravi Kumar", "Yugandhar Bitla", "I. S. Yahia", "S. AlFaify"],
      journal: "J. Inorg. Organomet. Polym. Mater.",
      year: 2021,
      volume: "31",
      pages: "2691",
      type: "journal",
      category: "co-author",
      isFirstAuthor: false,
      impactFactor: 2.1,
      citations: 7,
      link: "https://link.springer.com/article/10.1007/s10904-021-01889-3",
      doi: "10.1007/s10904-021-01889-3",
      abstract: "Studies properties of Nd-doped NiO thin films for electronic applications.",
      keywords: ["NiO", "Thin films", "Spray pyrolysis", "Dielectric properties", "Optical properties"]
    },

    // Conference proceedings
    {
      id: 14,
      title: "Thickness induced crossover from the ferromagnetic to cluster spin glass state in Cr70Fe30 thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "AIP Conf. Proc.",
      year: 2015,
      volume: "1665",
      pages: "030032",
      type: "conference",
      category: "conference",
      isFirstAuthor: true,
      link: "#",
      abstract: "Conference proceeding on thickness-induced magnetic crossover in CrFe thin films.",
      keywords: ["Conference proceedings", "Spin glass", "Thin films", "Magnetic crossover"]
    },
    {
      id: 15,
      title: "Critical behavior near ferromagnetic-paramagnetic phase transition in ion beam sputtered Cr70Fe30 thin films",
      authors: ["B. Ravi Kumar", "S. N. Kaul"],
      journal: "AIP Conf. Proc.",
      year: 2013,
      volume: "1536",
      pages: "953",
      type: "conference",
      category: "conference",
      isFirstAuthor: true,
      link: "#",
      abstract: "Conference proceeding on critical behavior in CrFe thin films.",
      keywords: ["Conference proceedings", "Phase transition", "Thin films", "Critical behavior"]
    },

    // Manuscripts under review
    {
      id: 16,
      title: "Enabling Electrical Readout of Néel vector reversal in a van der Waals Antiferromagnet",
      authors: ["Raghvendra", "B. Ravi Kumar", "et al."],
      journal: "Nature Communications (under review)",
      year: 2026,
      type: "under-review",
      category: "under-review",
      isFirstAuthor: false,
      link: "https://doi.org/10.48550/arXiv.2606.24527",
      arxiv: "https://doi.org/10.48550/arXiv.2606.24527",
      referenceNumber: "NCOMMS-26-049950-T",
      abstract: "Manuscript under review on electrical readout of Néel vector reversal in van der Waals antiferromagnets.",
      keywords: ["Van der Waals", "Antiferromagnet", "Néel vector", "Electrical readout", "2D materials"]
    },
    {
      id: 17,
      title: "Visualization of Tunable Electronic Structure of Monolayer TaIrTe4",
      authors: ["Sandy", "Aalok Tiwari", "B. Ravi Kumar", "Jyoti Katoch", "Simranjeet Singh", "et al."],
      journal: "Nature Communications (under review)",
      year: 2026,
      type: "under-review",
      category: "under-review",
      isFirstAuthor: false,
      link: "https://arxiv.org/abs/2601.11504",
      arxiv: "https://arxiv.org/abs/2601.11504",
      referenceNumber: "NCOMMS-26-004797",
      abstract: "Manuscript under review on visualization of tunable electronic structure of monolayer TaIrTe4.",
      keywords: ["TaIrTe4", "Monolayer", "Electronic structure", "2D materials", "ARPES"]
    },
    {
      id: 18,
      title: "Ultrafast light-induced magnetoelectric effect in van der Waals magnetic semiconductor heterostructures",
      authors: ["Wenyi", "B. Ravi Kumar", "Roland Kawakami", "et al."],
      journal: "Physical Review Letters (under review)",
      year: 2026,
      type: "under-review",
      category: "under-review",
      isFirstAuthor: false,
      link: "https://doi.org/10.48550/arXiv.2604.19080",
      arxiv: "https://doi.org/10.48550/arXiv.2604.19080",
      abstract: "Manuscript under review on ultrafast light-induced magnetoelectric effect in van der Waals heterostructures.",
      keywords: ["Van der Waals", "Magnetoelectric", "Ultrafast", "Heterostructures", "2D materials"]
    },

    // Ongoing works
    {
      id: 19,
      title: "Tilted Spin Polarization Enabled Multidimensional Unidirectional Magnetoresistance",
      authors: ["B. Ravi Kumar†", "I-Hsuan Kao†", "et al."],
      journal: "Ready for Submission",
      year: 2026,
      type: "ongoing",
      category: "ongoing",
      isFirstAuthor: true,
      isEquallyContributed: true,
      abstract: "Ongoing work on tilted spin polarization and multidimensional unidirectional magnetoresistance.",
      keywords: ["Spin polarization", "Magnetoresistance", "Ongoing work", "Spintronics"]
    },
    {
      id: 20,
      title: "Spatially Resolved Magnetism and Twist-Induced Domain Reconfiguration in Atomically Thin CrSBr",
      authors: ["Aalok Tiwari", "B. Ravi Kumar", "et al."],
      journal: "Ready for Submission",
      year: 2026,
      type: "ongoing",
      category: "ongoing",
      isFirstAuthor: false,
      abstract: "Ongoing work on spatially resolved magnetism and twist-induced domain reconfiguration in CrSBr.",
      keywords: ["CrSBr", "2D magnetism", "Domain reconfiguration", "Ongoing work"]
    },
    {
      id: 21,
      title: "Gate tunability of ferroelectricity in WTe2/CGT bilayer device",
      authors: ["Zhenhong Cui", "B. Ravi Kumar"],
      journal: "Manuscript in Preparation",
      year: 2026,
      type: "ongoing",
      category: "ongoing",
      isFirstAuthor: false,
      abstract: "Ongoing work on gate tunability of ferroelectricity in WTe2/CGT bilayer device.",
      keywords: ["Ferroelectricity", "WTe2", "CGT", "Bilayer", "Ongoing work"]
    },
    {
      id: 22,
      title: "Angle resolved Photoemission studies of microelectronic Devices and Quantum structures",
      authors: ["Aalok Tiwari", "B. Ravi Kumar", "et al."],
      journal: "Manuscript in Preparation",
      year: 2026,
      type: "ongoing",
      category: "ongoing",
      isFirstAuthor: false,
      abstract: "Ongoing work on angle resolved photoemission studies of microelectronic devices and quantum structures.",
      keywords: ["ARPES", "Microelectronic devices", "Quantum structures", "Ongoing work"]
    },
    {
      id: 23,
      title: "Tuning the field-like torque using multilayer stacks in CoFeB/Pt heterostructures",
      authors: ["B. Ravi Kumar", "P. S. Anil Kumar"],
      journal: "Manuscript in Preparation",
      year: 2026,
      type: "ongoing",
      category: "ongoing",
      isFirstAuthor: true,
      abstract: "Ongoing work on tuning field-like torque using multilayer stacks in CoFeB/Pt heterostructures.",
      keywords: ["Field-like torque", "CoFeB", "Pt", "Multilayer stacks", "Ongoing work"]
    }
  ];