  export const talksData = [
    {
      id: 1,
      title: "Unidirectional Magnetoresistance and Anomalous Hall Effects in Magnetic Thin Films",
      type: "conference",
      category: "conference",
      subcategory: "international",
      event: "APS March Meeting 2025",
      venue: "Los Angeles Convention Center",
      location: "Los Angeles, USA",
      date: "March 3-7, 2025",
      year: 2025,
      presentationType: "Oral Presentation",
      status: "upcoming",
      abstract: "Presenting experimental results on unidirectional magnetoresistance and anomalous Hall effects in magnetic thin film systems. Discussing the interplay between spin-orbit coupling and magnetic anisotropy.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: true,
      attendees: "800+",
      keywords: ["Unidirectional Magnetoresistance", "Anomalous Hall Effect", "Spintronics", "Thin Films"]
    },
    {
      id: 2,
      title: "Unidirectional Magnetoresistance and Anomalous Hall Effects in Magnetic Heterostructures",
      type: "conference",
      category: "conference",
      subcategory: "international",
      event: "APS March Meeting 2024",
      venue: "Minneapolis Convention Center",
      location: "Minneapolis, USA",
      date: "March 4-8, 2024",
      year: 2024,
      presentationType: "Oral Presentation",
      status: "presented",
      abstract: "Oral presentation on unidirectional magnetoresistance and anomalous Hall effects in magnetic heterostructures. Explored the role of interfacial spin-orbit coupling and its impact on transport properties.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: true,
      attendees: "700+",
      keywords: ["Unidirectional Magnetoresistance", "Anomalous Hall Effect", "Heterostructures", "Spin-Orbit Coupling"]
    },
    {
      id: 3,
      title: "Unidirectional Magnetoresistance and Anomalous Hall Effects in Magnetic Multilayers",
      type: "conference",
      category: "conference",
      subcategory: "international",
      event: "MMM & Intermag Conference 2024",
      venue: "San Diego Convention Center",
      location: "San Diego, USA",
      date: "June 4-8, 2024",
      year: 2024,
      presentationType: "Oral Presentation",
      status: "presented",
      abstract: "Presented findings on unidirectional magnetoresistance and anomalous Hall effects in magnetic multilayer systems. Investigated the thickness dependence and interfacial effects on magnetotransport properties.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: true,
      attendees: "600+",
      keywords: ["Unidirectional Magnetoresistance", "Anomalous Hall Effect", "Multilayers", "Interfacial Effects"]
    },
    {
      id: 4,
      title: "Advances in Spintronics: Magnetoresistance and Hall Effects in Magnetic Thin Films",
      type: "invited",
      category: "invited",
      subcategory: "international",
      event: "Symposium on Magnetism and Spintronics 2021",
      venue: "Indian Institute of Science",
      location: "Bangalore, India",
      date: "December 15-17, 2021",
      year: 2021,
      presentationType: "Invited Talk",
      status: "presented",
      abstract: "Invited talk covering recent advances in spintronics with focus on magnetoresistance and Hall effects in magnetic thin films. Discussed potential applications in next-generation memory and logic devices.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: true,
      attendees: "200+",
      keywords: ["Spintronics", "Magnetoresistance", "Hall Effects", "Memory Devices"]
    },
    {
      id: 5,
      title: "Magnetic Properties and Transport Phenomena in CrFe Alloy Thin Films",
      type: "conference",
      category: "conference",
      subcategory: "international",
      event: "International Conference on Magnetism and Magnetic Materials",
      venue: "Hilton San Francisco",
      location: "San Francisco, USA",
      date: "November 11-15, 2019",
      year: 2019,
      presentationType: "Poster Presentation",
      status: "presented",
      abstract: "Poster presentation on magnetic properties and transport phenomena in CrFe alloy thin films. Won Best Poster Award for this work.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: true,
      attendees: "500+",
      keywords: ["CrFe Alloy", "Thin Films", "Transport Properties", "Magnetic Properties"]
    },
    {
      id: 6,
      title: "Structural and Magnetic Characterization of Transition Metal Thin Films",
      type: "conference",
      category: "conference",
      subcategory: "national",
      event: "DAE Solid State Physics Symposium",
      venue: "BARC Convention Centre",
      location: "Mumbai, India",
      date: "December 18-22, 2018",
      year: 2018,
      presentationType: "Oral Presentation",
      status: "presented",
      abstract: "Presented structural and magnetic characterization studies of transition metal thin films. Discussed XRD, XPS, and SQUID measurements and their correlation with magnetic properties.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: false,
      attendees: "400+",
      keywords: ["Thin Films", "Characterization", "XRD", "XPS", "SQUID"]
    },
    {
      id: 7,
      title: "Frontiers in Magnetic Thin Film Research: From Fundamentals to Applications",
      type: "invited",
      category: "invited",
      subcategory: "international",
      event: "Frontiers in Physics Conference",
      venue: "Tata Institute of Fundamental Research",
      location: "Mumbai, India",
      date: "January 10-12, 2020",
      year: 2020,
      presentationType: "Invited Speaker",
      status: "presented",
      abstract: "Invited talk covering frontiers in magnetic thin film research, from fundamental physics to device applications. Highlighted recent breakthroughs and future directions.",
      slidesLink: "#",
      videoLink: "#",
      certificateLink: "#",
      featured: false,
      attendees: "300+",
      keywords: ["Magnetic Thin Films", "Applications", "Frontiers", "Spintronics"]
    }
  ];